<a href="https://colab.research.google.com/github/blackpearl-kd/Aarohini-Kriti25/blob/main/Trained_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/final_data.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
# Fill missing `Season` with mode
df['Production Units'] = df['Production Units'].fillna(df['Production Units'].mode()[0])

In [ ]:
# Fill missing values in 'Production', 'Yield', and 'Area' with mean of the same crop
for col in ['Production', 'Yield', 'Area']:
    df[col] = df.groupby('Crop')[col].transform(lambda x: x.fillna(x.mean()))
# Fill missing values in 'Season' with mode of the same crop
# Function to fill missing values with the mode of the same crop
def fill_mode(series):
    mode_value = series.mode()
    if not mode_value.empty:
        return series.fillna(mode_value.iloc[0])
    else:
        return series  # Return unchanged if there's no mode

df['Season'] = df.groupby('Crop')['Season'].transform(fill_mode)

In [ ]:
# Drop rows with any missing values
df = df.dropna()

# Verify if any missing values remain
df.isnull().sum()

State                                        0
District                                     0
Crop                                         0
Year                                         0
Season                                       0
Area                                         0
Production                                   0
Production Units                             0
Yield                                        0
Crop_Numeric                                 0
Investment per Hectare (INR)                 0
Average Expected Profit per Hectare (INR)    0
Nitrogen Impact                              0
dtype: int64

In [ ]:
# Group data by 'State'
state_group = df.groupby('State')

In [ ]:
# Generate summary statistics for each state
state_summary = state_group.describe()
print(state_summary)

                                Area                                       \
                               count          mean           std      min
State
Andaman and Nicobar Islands    524.0   1567.374061   4197.752862    0.110
Andhra Pradesh               12892.0  16144.427630  47066.614410    1.000
Arunachal Pradesh             2889.0   1633.320526   3355.902154    3.000
Assam                        14162.0   5228.160006  16105.143770    1.000
Bihar                        20641.0   5555.437769  17531.736915    1.000
Chandigarh                      95.0     43.421053     64.302407    1.000
Chhattisgarh                 12120.0   8575.418729  39770.270256    1.000
Dadra and Nagar Haveli         276.0   1581.692029   3475.593212    1.000
Daman and Diu                   42.0   1137.995238    827.724508  280.000
Delhi                          165.0   2026.224242   2899.223944    1.000
Goa                            353.0   7727.369688  11611.339089    0.100
Gujarat                      11977.0  15677.849144  45683.995954    1.000
Haryana                       6921.0  10537.947782  29314.868087    1.000
Himachal Pradesh              4087.0   2363.558845   7718.406244    1.000
Jammu and Kashmir             3733.0   3599.956335   9094.792185    1.000
Jharkhand                     4309.0   6568.868721  18418.959480    0.360
Karnataka                    22726.0   9756.761507  28066.442021    1.000
Kerala                        3664.0   9353.378329  20237.216981    0.004
Laddakh                          1.0    273.000000           NaN  273.000
Madhya Pradesh               23460.0  10121.920375  27320.887677    1.000
Maharashtra                  13924.0  25053.563085  62774.427229    1.000
Manipur                       2478.0   2234.023406   6007.416104    1.000
Meghalaya                     3179.0   1517.628185   3261.258208    1.000
Mizoram                       1639.0    902.471123   2452.378906    0.300
Nagaland                      4310.0   1684.459791   4553.858315    2.500
Odisha                       12833.0   9395.664225  33768.988033    1.000
Puducherry                     898.0    640.708241   1897.541936    1.000
Punjab                        3243.0  24766.574160  59128.858272  100.000
Rajasthan                    16962.0  23572.844653  72801.414892    1.000
Sikkim                         564.0   2569.675532   3828.475647   12.000
Tamil Nadu                   14483.0   6471.600773  18691.000657    1.000
Telangana                     3714.0   9936.524771  28976.341097    1.000
Tripura                       2014.0   3065.514399  12152.761060    1.000
Uttar Pradesh                34464.0   7595.177519  23158.690469    1.000
Uttarakhand                   5361.0   2201.578996   7627.734501    1.000
West Bengal                  10364.0  17048.789162  52186.203008    1.000

                                                                     \
                                25%      50%         75%        max
State
Andaman and Nicobar Islands   20.00   163.58    924.4975    43520.0
Andhra Pradesh               229.00  1601.50   9816.2500   877029.0
Arunachal Pradesh             70.00   230.00   1350.0000    25561.0
Assam                         89.00   450.00   2092.7500   152987.0
Bihar                         66.00   426.00   2402.0000   224721.0
Chandigarh                     8.00    20.00     55.0000      380.0
Chhattisgarh                  32.00   218.00   1122.0000   545965.0
Dadra and Nagar Haveli        60.00   200.00   1306.2500    14250.0
Daman and Diu                280.00  1050.15   2000.0000     2000.0
Delhi                         57.00   157.00   3161.0000     9273.0
Goa                          325.00  1500.00  12257.0000    54668.0
Gujarat                      300.00  1350.00   8000.0000   499100.0
Haryana                       50.00   318.00   2952.0000   225000.0
Himachal Pradesh              19.00   115.00    814.0000    58951.0
Jammu and Kashmir             22.00   118.00   1401.0000    79153.0
Jharkhand                    207.09   786.00   3500.0000   413835.1
Karnataka                     90.00   744.00   4947.2500   613760.0
Kerala                       220.00  1988.50   7089.2500   131061.0
Laddakh                      273.00   273.00    273.0000      273.0
Madhya Pradesh               108.00   928.00   6482.5000   537610.0
Maharashtra                  400.00  2500.00  18900.0000   765000.0
Manipur                       84.00   350.00   1200.0000    45380.0
Meghalaya                     63.00   265.00   1225.5000    40746.0
Mizoram                       30.00   115.00    555.0000    30274.0
Nagaland                     100.00   280.00    812.2500    50000.0
Odisha                        71.00   440.00   2079.0000   687000.0
Puducherry                     5.00    30.50    266.0000    18534.0
Punjab                       300.00  1000.00   5500.0000   400000.0
Rajasthan                     39.00   576.00   9947.0000  1133397.0
Sikkim                       420.00  1000.00   2310.0000    17280.0
Tamil Nadu                    67.00   689.00   4127.5000   207871.0
Telangana                     31.00   296.00   4628.7500   341655.0
Tripura                       73.00   223.00    511.7500   102480.0
Uttar Pradesh                 49.00   428.00   3656.2500   217806.0
Uttarakhand                   30.00   255.00   1087.0000   110438.0
West Bengal                  108.00   608.00   5353.2500   513019.0

                            Production                ...  Crop_Numeric  \
                                 count          mean  ...           75%
State                                                 ...
Andaman and Nicobar Islands      524.0  3.918413e+06  ...   6793.012802
Andhra Pradesh                 12892.0  2.011056e+06  ...   2111.284003
Arunachal Pradesh               2889.0  2.687166e+03  ...   2653.406028
Assam                          14162.0  2.549183e+05  ...   5351.055718
Bihar                          20641.0  1.229640e+04  ...   2653.406028
Chandigarh                        95.0  3.435846e+02  ...  13149.255690
Chhattisgarh                   12120.0  2.781529e+05  ...   2098.431054
Dadra and Nagar Haveli           276.0  4.446149e+03  ...   2098.431054
Daman and Diu                     42.0  1.411121e+03  ...   2098.431054
Delhi                            165.0  4.525533e+03  ...   2111.284003
Goa                              353.0  6.211931e+06  ...   2370.401573
Gujarat                        11977.0  3.693078e+04  ...   2098.431054
Haryana                         6921.0  2.836799e+04  ...   2098.431054
Himachal Pradesh                4087.0  5.080145e+03  ...   2653.406028
Jammu and Kashmir               3733.0  5.806313e+03  ...   2653.406028
Jharkhand                       4309.0  9.382416e+03  ...   2653.406028
Karnataka                      22726.0  2.774753e+06  ...   2653.406028
Kerala                          3664.0  3.538132e+07  ...   6793.012802
Laddakh                            1.0  1.092000e+02  ...    802.046080
Madhya Pradesh                 23460.0  1.520703e+04  ...   2098.431054
Maharashtra                    13924.0  2.725907e+04  ...   1311.281625
Manipur                         2478.0  5.941573e+03  ...   6785.424935
Meghalaya                       3179.0  4.782104e+03  ...   6762.661334
Mizoram                         1639.0  1.368936e+03  ...   2111.284003
Nagaland                        4310.0  3.189491e+03  ...   2098.431054
Odisha                         12833.0  1.333177e+04  ...   2098.431054
Puducherry                       898.0  5.439845e+05  ...   6762.661334
Punjab                          3243.0  8.988127e+04  ...   2098.431054
Rajasthan                      16962.0  2.149912e+04  ...   1916.122686
Sikkim                           564.0  4.324911e+03  ...   2098.431054
Tamil Nadu                     14483.0  5.368393e+06  ...   2370.401573
Telangana                       3714.0  3.335031e+04  ...   2111.284003
Tripura                         2014.0  7.873375e+03  ...   2098.431054
Uttar Pradesh                  34464.0  2.102929e+04  ...   2653.406028
Uttarakhand                     5361.0  4.534396e+03  ...   2653.406028
West Bengal                    10364.0  8.536035e+05  ...   2370.401573

                                          Nitrogen Impact                      \
                                      max           count      mean       std
State
Andaman and Nicobar Islands  29227.150350           524.0 -0.295802  0.664809
Andhra Pradesh               29227.150350         12892.0 -0.288939  0.819943
Arunachal Pradesh            13149.255690          2889.0 -0.546210  0.769952
Assam                        29227.150350         14162.0 -0.285977  0.788475
Bihar                        29227.150350         20641.0 -0.176251  0.911458
Chandigarh                   13178.672400            95.0 -0.673684  0.706235
Chhattisgarh                 29227.150350         12120.0 -0.066172  0.898557
Dadra and Nagar Haveli       29227.150350           276.0 -0.159420  0.867568
Daman and Diu                 2098.431054            42.0 -1.000000  0.000000
Delhi                        13149.255690           165.0 -0.593939  0.803172
Goa                          29227.150350           353.0 -0.178470  0.710626
Gujarat                      29227.150350         11977.0 -0.207398  0.848140
Haryana                      29227.150350          6921.0 -0.216587  0.892675
Himachal Pradesh             13178.672400          4087.0 -0.217274  0.903989
Jammu and Kashmir            13178.672400          3733.0 -0.267077  0.880710
Jharkhand                    13178.672400          4309.0 -0.207473  0.894702
Karnataka                    29227.150350         22726.0 -0.289052  0.818440
Kerala                       29227.150350          3664.0 -0.437773  0.579430
Laddakh                        802.046080             1.0 -1.000000       NaN
Madhya Pradesh               29227.150350         23460.0 -0.234825  0.851058
Maharashtra                  29227.150350         13924.0 -0.181198  0.807556
Manipur                      29227.150350          2478.0 -0.128329  0.937961
Meghalaya                    29227.150350          3179.0 -0.434413  0.746520
Mizoram                      13178.672400          1639.0 -0.115314  0.895384
Nagaland                     13149.255690          4310.0 -0.122042  0.868708
Odisha                       13178.672400         12833.0 -0.242422  0.797676
Puducherry                   29227.150350           898.0 -0.385301  0.724385
Punjab                        2653.406028          3243.0 -0.006475  0.880045
Rajasthan                    29227.150350         16962.0 -0.119679  0.875851
Sikkim                       13149.255690           564.0 -0.519504  0.740584
Tamil Nadu                   29227.150350         14483.0 -0.316371  0.786855
Telangana                    29227.150350          3714.0 -0.263059  0.859664
Tripura                      13149.255690          2014.0  0.027805  0.889426
Uttar Pradesh                29227.150350         34464.0 -0.241643  0.884497
Uttarakhand                  13178.672400          5361.0 -0.195299  0.890510
West Bengal                  13149.255690         10364.0 -0.093304  0.831841


                             min  25%  50%  75%  max
State
Andaman and Nicobar Islands -1.0 -1.0  0.0  0.0  1.0
Andhra Pradesh              -1.0 -1.0 -1.0  0.0  1.0
Arunachal Pradesh           -1.0 -1.0 -1.0  0.0  1.0
Assam                       -1.0 -1.0  0.0  0.0  1.0
Bihar                       -1.0 -1.0 -1.0  1.0  1.0
Chandigarh                  -1.0 -1.0 -1.0 -1.0  1.0
Chhattisgarh                -1.0 -1.0  0.0  1.0  1.0
Dadra and Nagar Haveli      -1.0 -1.0  0.0  1.0  1.0
Daman and Diu               -1.0 -1.0 -1.0 -1.0 -1.0
Delhi                       -1.0 -1.0 -1.0 -1.0  1.0
Goa                         -1.0 -1.0  0.0  0.0  1.0
Gujarat                     -1.0 -1.0  0.0  1.0  1.0
Haryana                     -1.0 -1.0 -1.0  1.0  1.0
Himachal Pradesh            -1.0 -1.0 -1.0  1.0  1.0
Jammu and Kashmir           -1.0 -1.0 -1.0  1.0  1.0
Jharkhand                   -1.0 -1.0 -1.0  1.0  1.0
Karnataka                   -1.0 -1.0 -1.0  0.0  1.0
Kerala                      -1.0 -1.0  0.0  0.0  1.0
Laddakh                     -1.0 -1.0 -1.0 -1.0 -1.0
Madhya Pradesh              -1.0 -1.0 -1.0  1.0  1.0
Maharashtra                 -1.0 -1.0  0.0  1.0  1.0
Manipur                     -1.0 -1.0 -1.0  1.0  1.0
Meghalaya                   -1.0 -1.0 -1.0  0.0  1.0
Mizoram                     -1.0 -1.0  0.0  1.0  1.0
Nagaland                    -1.0 -1.0  0.0  1.0  1.0
Odisha                      -1.0 -1.0  0.0  0.0  1.0
Puducherry                  -1.0 -1.0 -1.0  0.0  1.0
Punjab                      -1.0 -1.0  0.0  1.0  1.0
Rajasthan                   -1.0 -1.0  0.0  1.0  1.0
Sikkim                      -1.0 -1.0 -1.0  0.0  1.0
Tamil Nadu                  -1.0 -1.0 -1.0  0.0  1.0
Telangana                   -1.0 -1.0 -1.0  1.0  1.0
Tripura                     -1.0 -1.0  0.0  1.0  1.0
Uttar Pradesh               -1.0 -1.0 -1.0  1.0  1.0
Uttarakhand                 -1.0 -1.0 -1.0  1.0  1.0
West Bengal                 -1.0 -1.0  0.0  1.0  1.0

[36 rows x 40 columns]

In [ ]:
# Total area and production by state
state_area_production = state_group[['Area', 'Production']].sum()
print(state_area_production)

                                     Area    Production
State
Andaman and Nicobar Islands  8.213040e+05  2.053249e+09
Andhra Pradesh               2.081340e+08  2.592653e+10
Arunachal Pradesh            4.718663e+06  7.763221e+06
Assam                        7.404120e+07  3.610154e+09
Bihar                        1.146698e+08  2.538099e+08
Chandigarh                   4.125000e+03  3.264053e+04
Chhattisgarh                 1.039341e+08  3.371213e+09
Dadra and Nagar Haveli       4.365470e+05  1.227137e+06
Daman and Diu                4.779580e+04  5.926708e+04
Delhi                        3.343270e+05  7.467130e+05
Goa                          2.727762e+06  2.192812e+09
Gujarat                      1.877736e+08  4.423200e+08
Haryana                      7.293314e+07  1.963348e+08
Himachal Pradesh             9.659865e+06  2.076255e+07
Jammu and Kashmir            1.343864e+07  2.167497e+07
Jharkhand                    2.830526e+07  4.042883e+07
Karnataka                    2.217322e+08  6.305904e+10
Kerala                       3.427078e+07  1.296372e+11
Laddakh                      2.730000e+02  1.092000e+02
Madhya Pradesh               2.374603e+08  3.567570e+08
Maharashtra                  3.488458e+08  3.795553e+08
Manipur                      5.535910e+06  1.472322e+07
Meghalaya                    4.824540e+06  1.520231e+07
Mizoram                      1.479150e+06  2.243687e+06
Nagaland                     7.260022e+06  1.374671e+07
Odisha                       1.205746e+08  1.710866e+08
Puducherry                   5.753560e+05  4.884981e+08
Punjab                       8.031800e+07  2.914850e+08
Rajasthan                    3.998426e+08  3.646681e+08
Sikkim                       1.449297e+06  2.439250e+06
Tamil Nadu                   9.372819e+07  7.775044e+10
Telangana                    3.690425e+07  1.238630e+08
Tripura                      6.173946e+06  1.585698e+07
Uttar Pradesh                2.617602e+08  7.247536e+08
Uttarakhand                  1.180266e+07  2.430890e+07
West Bengal                  1.766937e+08  8.846747e+09

In [ ]:
# Average yield by state
state_yield = state_group['Yield'].mean()
print(state_yield)

State
Andaman and Nicobar Islands    446.678314
Andhra Pradesh                 266.680511
Arunachal Pradesh                2.683224
Assam                          291.657978
Bihar                            2.358670
Chandigarh                       9.386833
Chhattisgarh                     2.022280
Dadra and Nagar Haveli          11.443288
Daman and Diu                    1.353135
Delhi                            8.861503
Goa                            404.119002
Gujarat                          4.474821
Haryana                          4.136611
Himachal Pradesh                 1.955499
Jammu and Kashmir                1.923655
Jharkhand                        2.305180
Karnataka                      188.019378
Kerala                         552.993134
Laddakh                          0.400000
Madhya Pradesh                   2.904980
Maharashtra                      1.676370
Manipur                          3.207538
Meghalaya                        3.114918
Mizoram                          1.606733
Nagaland                         1.858684
Odisha                           1.585453
Puducherry                     973.228855
Punjab                           1.854385
Rajasthan                        1.641050
Sikkim                           1.359904
Tamil Nadu                     381.258708
Telangana                       25.481537
Tripura                          1.970466
Uttar Pradesh                    3.845225
Uttarakhand                      2.719536
West Bengal                    520.097669
Name: Yield, dtype: float64

In [ ]:
# Count of crops grown in each state
state_crop_distribution = df.groupby(['State', 'Crop']).size().unstack(fill_value=0)
print(state_crop_distribution)

Crop                         arecanut  arhar/tur  bajra  banana  barley  \
State
Andaman and Nicobar Islands        51         15      0      49       0
Andhra Pradesh                     60        654    558     313       0
Arunachal Pradesh                   0         62      0       0       0
Assam                             568        589      0     543       0
Bihar                               0        875    247     231     733
Chandigarh                          0          3      0       0       0
Chhattisgarh                        0        430    115     369     159
Dadra and Nagar Haveli              0         25      0       9       0
Daman and Diu                       0          0     21       0       0
Delhi                               0          4     22       0      22
Goa                                20          0      0      20       0
Gujarat                             0        548    962     225       0
Haryana                             0        382    447       8     402
Himachal Pradesh                    0         80    108       0     244
Jammu and Kashmir                   0          2    115       0     198
Jharkhand                           0        391     30       0       4
Karnataka                         443        586    505     333       0
Kerala                            322         21      0     308       0
Laddakh                             0          0      0       0       0
Madhya Pradesh                      0       1120    705     324     816
Maharashtra                         0        731    491      28       0
Manipur                             0         99      0     200       0
Meghalaya                         173         80      0     175       0
Mizoram                             0        103      0       0       0
Nagaland                            0        196    183       0     161
Odisha                              0        252     78       0       0
Puducherry                         17          0     32      64       0
Punjab                              0        263     76       0     218
Rajasthan                           0        555    742      90     747
Sikkim                              0          0      0       0      89
Tamil Nadu                        349        544    697     569       0
Telangana                           0        227    106     121       0
Tripura                             0        100      0       0       0
Uttar Pradesh                       0       1445   1492     530    1675
Uttarakhand                         0        229     16       0     273
West Bengal                       189        284     48       0     150

Crop                         black pepper  cardamom  cashewnut  castor seed  \
State
Andaman and Nicobar Islands            47         0         45            0
Andhra Pradesh                          4         0        256          364
Arunachal Pradesh                       0         0          0            0
Assam                                 350         0          0          519
Bihar                                   0         0          0          102
Chandigarh                              0         0          0            0
Chhattisgarh                            0         0          0          124
Dadra and Nagar Haveli                  0         0          0            0
Daman and Diu                           0         0          0            0
Delhi                                   0         0          0            0
Goa                                    28         0         28            0
Gujarat                                 0         0          0          529
Haryana                                 0         0          0           67
Himachal Pradesh                        0         0          0            0
Jammu and Kashmir                       0         0          0            0
Jharkhand                               0         0          0           14
Karnataka                             309       184        268          483
Kerala                                322       184        322            0
Laddakh                                 0         0          0            0
Madhya Pradesh                          0         0          1          295
Maharashtra                             0         0          0          422
Manipur                                 0         0         11            0
Meghalaya                             119         0         50           73
Mizoram                                 0         0          0            0
Nagaland                                0        17          0          112
Odisha                                  0         0          0          332
Puducherry                             18         0         51            0
Punjab                                  0         0          0            0
Rajasthan                               0         0          0          558
Sikkim                                  0         0          0            0
Tamil Nadu                            220       180        516          496
Telangana                               0         0         25          136
Tripura                                 0         0          0            0
Uttar Pradesh                           0         0          0           35
Uttarakhand                             0         0          0            0
West Bengal                             0        10          0           20

Crop                         coconut  ...  other summer pulses  \
State                                 ...
Andaman and Nicobar Islands       48  ...                    0
Andhra Pradesh                   297  ...                    0
Arunachal Pradesh                  0  ...                    0
Assam                            567  ...                    0
Bihar                              0  ...                    0
Chandigarh                         0  ...                    0
Chhattisgarh                      30  ...                    0
Dadra and Nagar Haveli             9  ...                    0
Daman and Diu                      0  ...                    0
Delhi                              0  ...                    0
Goa                               28  ...                    0
Gujarat                            0  ...                    0
Haryana                            0  ...                    0
Himachal Pradesh                   0  ...                    0
Jammu and Kashmir                  0  ...                    0
Jharkhand                          0  ...                    0
Karnataka                        627  ...                    0
Kerala                           322  ...                    0
Laddakh                            0  ...                    0
Madhya Pradesh                     0  ...                    0
Maharashtra                        0  ...                   61
Manipur                            0  ...                    0
Meghalaya                          0  ...                    0
Mizoram                            2  ...                    0
Nagaland                           0  ...                    0
Odisha                             0  ...                    0
Puducherry                        77  ...                    4
Punjab                             0  ...                    0
Rajasthan                          0  ...                    0
Sikkim                             0  ...                    0
Tamil Nadu                       487  ...                    0
Telangana                          4  ...                    0
Tripura                            0  ...                    0
Uttar Pradesh                      0  ...                    0
Uttarakhand                        0  ...                    2
West Bengal                      429  ...                    0

Crop                         peas & beans (pulses)  potato  ragi  \
State
Andaman and Nicobar Islands                      0       0     0
Andhra Pradesh                                   0     120   520
Arunachal Pradesh                              165     364     0
Assam                                          497     589     0
Bihar                                          763     776   685
Chandigarh                                       0      18     0
Chhattisgarh                                   401     521   254
Dadra and Nagar Haveli                           0       0    21
Daman and Diu                                    0       0     0
Delhi                                            0      16     0
Goa                                              0       0    30
Gujarat                                          0     270    83
Haryana                                        392     370     0
Himachal Pradesh                               284     345   109
Jammu and Kashmir                              256     391    11
Jharkhand                                      104     539   265
Karnataka                                      211     673  1112
Kerala                                           0      24    54
Laddakh                                          0       0     0
Madhya Pradesh                                 681     928    88
Maharashtra                                      0       0   273
Manipur                                        201     178     0
Meghalaya                                      105     248     0
Mizoram                                         31     114     0
Nagaland                                       367     217    77
Odisha                                          30     639   826
Puducherry                                       0       0    53
Punjab                                         127       0     0
Rajasthan                                      537     614     0
Sikkim                                           0       8     0
Tamil Nadu                                       0     142   748
Telangana                                        0      39    81
Tripura                                        100      20     0
Uttar Pradesh                                 1383    1684   119
Uttarakhand                                    269     462   233
West Bengal                                    362     447   115

Crop                         rapeseed &mustard  rice  safflower  sannhamp  \
State
Andaman and Nicobar Islands                 15    47          1         0
Andhra Pradesh                             129   893        146        14
Arunachal Pradesh                          109   380          0         0
Assam                                      589  1756          0         0
Bihar                                      899  2093        148       407
Chandigarh                                   5    22          0         0
Chhattisgarh                               430   430        204       361
Dadra and Nagar Haveli                       9    39          0        13
Daman and Diu                                0    21          0         0
Delhi                                        1    22          0         0
Goa                                          0    70          0         0
Gujarat                                    462   568          0         0
Haryana                                    423   448          0       132
Himachal Pradesh                           221   242          0        17
Jammu and Kashmir                          317   327          0        55
Jharkhand                                  384   671         28         0
Karnataka                                  380  1538        340       127
Kerala                                       0   900          0         0
Laddakh                                      0     0          0         0
Madhya Pradesh                            1072  1082        241       500
Maharashtra                                473   874        425         0
Manipur                                    121   206          0         0
Meghalaya                                  189   473          0         0
Mizoram                                    103   279          0         0
Nagaland                                   203   263          0         0
Odisha                                     632  1684         63        55
Puducherry                                   7   151          0         0
Punjab                                     392   448          0         0
Rajasthan                                  748   483          0       452
Sikkim                                      92    92          0         0
Tamil Nadu                                 131   829          0        36
Telangana                                   12   305         55         0
Tripura                                    100   224          0         0
Uttar Pradesh                             1683  2142          0       679
Uttarakhand                                273   330          0         1
West Bengal                                430  1279        113       168

Crop                         sesamum  small millets
State
Andaman and Nicobar Islands       13              0
Andhra Pradesh                   763            221
Arunachal Pradesh                 91            241
Assam                            589            372
Bihar                            632            314
Chandigarh                         0              0
Chhattisgarh                     430            305
Dadra and Nagar Haveli             8             15
Daman and Diu                      0              0
Delhi                              0              0
Goa                                0              0
Gujarat                          715             83
Haryana                          347              0
Himachal Pradesh                 182             95
Jammu and Kashmir                 94             54
Jharkhand                         62              0
Karnataka                        574            281
Kerala                           221             13
Laddakh                            0              0
Madhya Pradesh                  1069            510
Maharashtra                      931            657
Manipur                           27              0
Meghalaya                        178             84
Mizoram                          121              0
Nagaland                         204            100
Odisha                          1214             71
Puducherry                        59              5
Punjab                           236              0
Rajasthan                        745            151
Sikkim                             0             48
Tamil Nadu                       806            203
Telangana                        209              0
Tripura                          100              0
Uttar Pradesh                   1474            352
Uttarakhand                      264             68
West Bengal                      691             92

[36 rows x 46 columns]

In [ ]:
# Count rows where 'Production Units' is not 'Tonnes'
count_production_units = len(df[df['Production Units'] != 'Tonnes'])



# Display the counts
print("Number of rows where 'Production Units' is NOT 'Tonnes':", count_production_units)

Number of rows where 'Production Units' is NOT 'Tonnes': 13721

In [ ]:
# Function to replace range values with their mean
def replace_range_with_mean(value):
    if isinstance(value, str) and '-' in value:  # Check if the value is a string and contains '-'
        try:
            # Remove commas and split the range into two numbers
            min_val, max_val = value.replace(',', '').split('-')
            mean_val = (int(min_val) + int(max_val)) // 2  # Compute mean
            return mean_val
        except:
            return np.nan  # Return NaN if parsing fails
    return value  # Keep value unchanged if it's not a range

# Apply the function to the column
df['Average Expected Profit per Hectare (INR)'] = df['Average Expected Profit per Hectare (INR)'].apply(replace_range_with_mean)

# Convert column to integer type (if all values are now numeric)
df['Average Expected Profit per Hectare (INR)'] = pd.to_numeric(df['Average Expected Profit per Hectare (INR)'], errors='coerce')

In [ ]:
# Function to replace range values with their mean
def replace_range_with_mean(value):
    if isinstance(value, str) and '-' in value:  # Check if the value is a string and contains '-'
        try:
            # Remove commas and split the range into two numbers
            min_val, max_val = value.replace(',', '').split('-')
            mean_val = (int(min_val) + int(max_val)) // 2  # Compute mean
            return mean_val
        except:
            return np.nan  # Return NaN if parsing fails
    return value  # Keep value unchanged if it's not a range

# Apply the function to the column
df['Investment per Hectare (INR)'] = df['Investment per Hectare (INR)'].apply(replace_range_with_mean)

# Convert column to integer type (if all values are now numeric)
df['Investment per Hectare (INR)'] = pd.to_numeric(df['Investment per Hectare (INR)'], errors='coerce')

In [ ]:
df['Year'] = df['Year'].str.split('-').str[0]
df.head()

,State,District,Crop,Year,Season,Area,Production,Production Units,Yield,Crop_Numeric,Investment per Hectare (INR),Average Expected Profit per Hectare (INR),Nitrogen Impact
0,Andaman and Nicobar Islands,NICOBARS,arecanut,2001,Kharif,1254.0,2061.0,Tonnes,1.643541,2370.401573,50000.0,30000.0,0.0
1,Andaman and Nicobar Islands,NICOBARS,arecanut,2002,Whole Year,1258.0,2083.0,Tonnes,1.655803,2370.401573,50000.0,30000.0,0.0
2,Andaman and Nicobar Islands,NICOBARS,arecanut,2003,Whole Year,1261.0,1525.0,Tonnes,1.209358,2370.401573,50000.0,30000.0,0.0
3,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,arecanut,2001,Kharif,3100.0,5239.0,Tonnes,1.690000,2370.401573,50000.0,30000.0,0.0
4,Andaman and Nicobar Islands,SOUTH ANDAMANS,arecanut,2002,Whole Year,3105.0,5267.0,Tonnes,1.696296,2370.401573,50000.0,30000.0,0.0

In [ ]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df.shape

(275467, 13)

In [ ]:
df.head()

,State,District,Crop,Year,Season,Area,Production,Production Units,Yield,Crop_Numeric,Investment per Hectare (INR),Average Expected Profit per Hectare (INR),Nitrogen Impact
0,Madhya Pradesh,GUNA,gram,2013,Rabi,79602.0,77262.0,Tonnes,0.970604,878.775417,32500.0,18500.0,1.0
1,Tamil Nadu,PERAMBALUR,groundnut,2010,Kharif,1417.0,1963.0,Tonnes,1.385321,1311.281625,40000.0,22500.0,0.0
2,Assam,BARPETA,moong(green gram),2016,Rabi,349.0,221.0,Tonnes,0.633238,492.161955,20000.0,11500.0,1.0
3,Madhya Pradesh,KHANDWA,castor seed,2003,Kharif,91.0,24.0,Tonnes,0.263736,728.134043,20000.0,11500.0,0.0
4,Uttar Pradesh,BALRAMPUR,rapeseed &mustard,2013,Rabi,17396.0,15135.0,Tonnes,0.870028,824.314297,32500.0,18500.0,0.0

In [ ]:
import pandas as pd

def allocate_crops(df, state, district, season, total_investment, total_area):
    # Filter the dataset based on the input parameters
    filtered_data = df[
        (df['State'] == state) &
        (df['District'] == district) &
        (df['Season'] == season)
    ].copy()

    if filtered_data.empty:
        return "No crops available for the given inputs."

    # Compute Profit/Investment ratio
    filtered_data['profit_ratio'] = filtered_data['Average Expected Profit per Hectare (INR)'] / filtered_data['Investment per Hectare (INR)']

    # Segregate crops based on nitrogen impact
    crops_nitrogen_plus = filtered_data[filtered_data['Nitrogen Impact'] == 1].sort_values(by='profit_ratio', ascending=False)
    crops_nitrogen_minus = filtered_data[filtered_data['Nitrogen Impact'] == -1].sort_values(by='profit_ratio', ascending=False)
    crops_nitrogen_neutral = filtered_data[filtered_data['Nitrogen Impact'] == 0].sort_values(by='profit_ratio', ascending=False)

    # Lists of crops to iterate over
    nitrogen_crops = [crops_nitrogen_plus, crops_nitrogen_neutral, crops_nitrogen_minus]

    # Initialize tracking variables
    total_area_used = 0
    remaining_investment = total_investment
    crop_allocation = {}

    # Iterate through each crop list in round-robin manner
    crop_indices = [0, 0, 0]  # Track which crop is picked next in each category
    while remaining_investment > 0 and total_area_used < total_area:
        for i, crop_list in enumerate(nitrogen_crops):
            if crop_indices[i] < len(crop_list):  # Check if there are remaining crops in the list
                crop = crop_list.iloc[crop_indices[i]]
                crop_indices[i] += 1  # Move to next crop in the category

                # Extract crop details
                crop_name = crop['Crop']
                investment_per_hectare = crop['Investment per Hectare (INR)']
                area_per_hectare = 1  # Assuming 1 hectare per unit

                # Maximum area that can be allocated for this crop
                max_area_by_investment = remaining_investment / investment_per_hectare
                max_area_by_land = total_area - total_area_used
                area_allocated = min(max_area_by_investment, max_area_by_land, area_per_hectare)

                if area_allocated > 0:
                    # Store allocation
                    if crop_name in crop_allocation:
                        crop_allocation[crop_name] += area_allocated
                    else:
                        crop_allocation[crop_name] = area_allocated

                    # Deduct investment
                    remaining_investment -= (area_allocated * investment_per_hectare)

                    # Update total area used
                    total_area_used += area_allocated

                # Stop if either investment or area is exhausted
                if remaining_investment <= 0 or total_area_used >= total_area:
                    break

    return crop_allocation

# Example usage:
state_input = "Madhya Pradesh"
district_input = "GUNA"
season_input = "Rabi"
total_investment_input = 150000  # Example value
total_area_input = 50  # Example total area in hectares

# Call the function with `df`
crop_allocation_result = allocate_crops(df, state_input, district_input, season_input, total_investment_input, total_area_input)

# Print the output in the required format
print("The area to be used for cropping for each crop based on optimal nitrogen impact and profit is:")
for crop, area in crop_allocation_result.items():
    print(f"{crop}: {area:.2f} hectares")

The area to be used for cropping for each crop based on optimal nitrogen impact and profit is:
masoor: 2.40 hectares
linseed: 2.00 hectares
barley: 2.00 hectares